[phases.setup]
nixPkgs = ["...", "unzip"]

[phases.build]
cmds = ["python -m venv .venv", ". .venv/bin/activate", "pip install -r requirements.txt", "reflex export --frontend-only", "unzip frontend.zip -d .web", "rm frontend.zip"]

[start]
cmd = "reflex run --env prod --backend-port $PORT --backend-host 0.0.0.0"
